version: "3.9"  # optional since v1.27.0
services:
  web31:
    build: .
    ports:
      - "80:80"
  web231:
    build: .
    ports:
      - "80:80"
  web3551:
    build: .
    ports:
      - "80:80"
  web23431:
    build: .
    ports:
      - "80:80"
